import type { Metadata } from "next";
import "./globals.css";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "IFRS16 Calculation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
